- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy index.html to /var/www/html
  copy:
    src: /home/ruzal/ansible/roles/files/html/index.html
    dest: /var/www/html/

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted